version: '3'
services:
  site:
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./clean-blog:/var/www/html/user/themes/clean-blog"
      - "./pages:/var/www/html/user/pages"
    build:
      context: .
      dockerfile: Dockerfile
